import {
  ReactLogo,
  JavascriptLogo,
  MUILogo,
  GraphqlLogo,
  TypescriptLogo,
  MongoDBLogo,
  AwsLambdaLogo,
  AngularLogo,
  GithubLogo,
  BitbucketLogo,
  NodeJsLogo,
  DynamoDBLogo,
} from "../../assets/images";

export const COURSES = [
  "Honors Data Structures & Algorithms",
  "Pega Systems Architect",
  "VR App Development",
  "Computer Security",
  "Software Engineer Lab I & II",
  "UNIX Programming",
  "Analysis of Algorithms",
  "Embedded Systems",
  "Computer Software & Operating Systems",
  "Computer Networks",
  "Physics I & II",
  "Calculus I & II",
];

export const SKILLS = [
  {
    image: ReactLogo,
    title: "React",
    height: "5rem",
    width: "6rem",
    experienceInYears: "2.5",
  },
  {
    image: AngularLogo,
    title: "Angular",
    height: "5rem",
    width: "5rem",
    experienceInYears: "1",
  },
  {
    image: GraphqlLogo,
    title: "GraphQL",
    height: "5rem",
    width: "5rem",
    experienceInYears: "1.5",
  },
  {
    image: TypescriptLogo,
    title: "TypeScript",
    height: "5rem",
    width: "5rem",
    experienceInYears: "2.5",
  },
  {
    image: JavascriptLogo,
    title: "JavaScript",
    height: "5rem",
    width: "5rem",
    experienceInYears: "3",
  },
  {
    image: NodeJsLogo,
    title: "Node.js",
    height: "5rem",
    width: "5rem",
    experienceInYears: "2",
  },
  {
    image: MongoDBLogo,
    title: "MongoDB",
    height: "5rem",
    width: "5rem",
    experienceInYears: "2.5",
  },
  {
    image: DynamoDBLogo,
    title: "DynamoDB",
    height: "5rem",
    width: "5rem",
    experienceInYears: "1.5",
  },
  {
    image: AwsLambdaLogo,
    title: "AWS Lambda",
    height: "5rem",
    width: "5rem",
    experienceInYears: "1",
  },
  {
    image: MUILogo,
    title: "Material UI",
    height: "5rem",
    width: "5rem",
    experienceInYears: "3.5",
  },
  {
    image: GithubLogo,
    title: "Github",
    height: "5rem",
    width: "5rem",
    experienceInYears: "3.5",
  },
  {
    image: BitbucketLogo,
    title: "Bitbucket",
    height: "5rem",
    width: "5rem",
    experienceInYears: "3.5",
  },
];
